import PDFDocument from "pdfkit";
import { Buffer } from "buffer";
import { getLessonPlanFramework } from "@/lib/lesson-plan-frameworks";

export interface LessonPlanDay {
  day: number;
  topic: string;
  "4asModel": Array<{
    phase: string;
    title: string;
    timeMinutes: number;
    description: string;
    teacherRole: string;
    studentRole: string;
    materials: string[];
  }>;
  specificActivities: {
    ACTIVITY?: {
      type: string;
      readingPassage: string;
      questions: Array<{ question: string; answer: string }>;
    };
    ANALYSIS?: {
      type: string;
      trueFalse: Array<{ statement: string; answer: string; explanation: string }>;
      checklist: string[];
    };
    ABSTRACTION?: {
      type: string;
      pairs: Array<{ left: string; right: string }>;
      explanation: string;
    };
    APPLICATION?: {
      type: string;
      multipleChoice: Array<{
        question: string;
        options: string[];
        answer: string;
        explanation: string;
      }>;
      identification: { clues: string[]; wordBank: string[]; answers: string[] };
    };
  };
  assessment: Array<{
    criteria: string;
    description: string;
    rubricLevel: {
      excellent: string;
      satisfactory: string;
      needsImprovement: string;
    };
  }>;
  differentiation: string;
  closure: string;
}

export interface LessonPlanData {
  title: string;
  framework?: string;
  frameworkLabel?: string;
  grade: string;
  duration: string;
  objectives: string[];
  days: LessonPlanDay[];
}

const MARGIN = 54;
const CONTENT_WIDTH = 612 - MARGIN * 2;

function sanitize(text: unknown): string {
  return String(text ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

function ensureSpace(doc: PDFKit.PDFDocument, needed = 28) {
  const usableBottom = doc.page.height - doc.page.margins.bottom - 20;
  if (doc.y + needed > usableBottom) doc.addPage();
}

function heading(doc: PDFKit.PDFDocument, text: string, level: 1 | 2 | 3 = 2) {
  ensureSpace(doc, level === 1 ? 40 : 30);
  const size = level === 1 ? 18 : level === 2 ? 14 : 11;
  const color = level === 1 ? "#0f172a" : "#1e3a8a";
  doc.font("Helvetica-Bold").fontSize(size).fillColor(color).text(text, MARGIN, doc.y, {
    width: CONTENT_WIDTH,
  });
  doc.moveDown(level === 1 ? 0.55 : 0.35);
}

function paragraph(doc: PDFKit.PDFDocument, text: string, opts?: { size?: number; color?: string }) {
  const value = sanitize(text);
  if (!value) return;
  ensureSpace(doc, 20);
  doc
    .font("Helvetica")
    .fontSize(opts?.size ?? 10)
    .fillColor(opts?.color ?? "#334155")
    .text(value, MARGIN, doc.y, { width: CONTENT_WIDTH, lineGap: 2, align: "left" });
  doc.moveDown(0.22);
}

function labeledParagraph(doc: PDFKit.PDFDocument, label: string, value: string) {
  const clean = sanitize(value);
  if (!clean) return;
  ensureSpace(doc, 22);
  doc
    .font("Helvetica-Bold")
    .fontSize(9.5)
    .fillColor("#0f172a")
    .text(`${label}: `, MARGIN, doc.y, { continued: true });
  doc.font("Helvetica").fontSize(9.5).fillColor("#334155").text(clean, {
    width: CONTENT_WIDTH,
    lineGap: 2,
  });
  doc.moveDown(0.1);
}

function bullet(doc: PDFKit.PDFDocument, text: string, indent = 0) {
  const clean = sanitize(text);
  if (!clean) return;
  ensureSpace(doc, 20);
  const x = MARGIN + indent;
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1d4ed8").text("•", x, doc.y, { continued: true });
  doc.font("Helvetica").fontSize(10).fillColor("#334155").text(` ${clean}`, {
    width: CONTENT_WIDTH - indent - 8,
    lineGap: 2,
  });
}

function addFooter(doc: PDFKit.PDFDocument) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    const y = doc.page.height - 26;
    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor("#64748b")
      .text(`Page ${i + 1} of ${range.count}`, MARGIN, y, { width: CONTENT_WIDTH / 2, align: "left" });
    doc
      .font("Helvetica-Oblique")
      .fontSize(8.5)
      .fillColor("#94a3b8")
      .text("Generated by QuizMintAI", MARGIN + CONTENT_WIDTH / 2, y, {
        width: CONTENT_WIDTH / 2,
        align: "right",
      });
  }
}

function renderSpecificActivities(doc: PDFKit.PDFDocument, activities: LessonPlanDay["specificActivities"]) {
  const entries = Object.entries(activities || {});
  if (!entries.length) return;
  heading(doc, "Specific Activities", 2);

  for (const [phase, raw] of entries) {
    const activity = raw as any;
    if (!activity) continue;
    heading(doc, `${phase} - ${sanitize(activity.type || "Activity")}`, 3);

    if (phase === "ACTIVITY") {
      labeledParagraph(doc, "Reading Passage", activity.readingPassage);
      for (const [i, q] of (activity.questions || []).entries()) {
        bullet(doc, `Q${i + 1}: ${sanitize(q?.question)}`);
        labeledParagraph(doc, "Answer", sanitize(q?.answer));
      }
    }

    if (phase === "ANALYSIS") {
      for (const [i, tf] of (activity.trueFalse || []).entries()) {
        bullet(doc, `${i + 1}. ${sanitize(tf?.statement)}`);
        labeledParagraph(doc, "Expected", sanitize(tf?.answer));
        labeledParagraph(doc, "Explanation", sanitize(tf?.explanation));
      }
      for (const item of activity.checklist || []) bullet(doc, item);
    }

    if (phase === "ABSTRACTION") {
      for (const pair of activity.pairs || []) {
        bullet(doc, `${sanitize(pair?.left)} -> ${sanitize(pair?.right)}`);
      }
      labeledParagraph(doc, "Explanation", sanitize(activity.explanation));
    }

    if (phase === "APPLICATION") {
      for (const [i, mc] of (activity.multipleChoice || []).entries()) {
        bullet(doc, `Q${i + 1}: ${sanitize(mc?.question)}`);
        for (const [idx, option] of (mc?.options || []).entries()) {
          const letter = String.fromCharCode(97 + idx);
          bullet(doc, `${letter}) ${sanitize(option)}`, 14);
        }
        labeledParagraph(doc, "Answer", sanitize(mc?.answer));
        labeledParagraph(doc, "Explanation", sanitize(mc?.explanation));
      }

      const clues = activity.identification?.clues || [];
      const answers = activity.identification?.answers || [];
      for (const [i, clue] of clues.entries()) {
        bullet(doc, `Clue ${i + 1}: ${sanitize(clue)}`);
        labeledParagraph(doc, "Answer", sanitize(answers[i]));
      }
    }

    doc.moveDown(0.25);
  }
}

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderList(items: unknown[], ordered = false) {
  const clean = (items || []).map((item) => sanitize(item)).filter(Boolean);
  if (!clean.length) return "";
  const tag = ordered ? "ol" : "ul";
  return `<${tag}>${clean.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</${tag}>`;
}

function contentLength(value: unknown) {
  return sanitize(value).length;
}

function shouldAvoidBreak(value: unknown, threshold = 420) {
  return contentLength(value) > 0 && contentLength(value) <= threshold;
}

function renderCard(
  title: string,
  body: string,
  options?: { threshold?: number; extraClass?: string }
) {
  const threshold = options?.threshold ?? 420;
  const cardClass = shouldAvoidBreak(`${title} ${body}`, threshold)
    ? "card avoid-break"
    : "card";
  return `
    <div class="${cardClass}${options?.extraClass ? ` ${options.extraClass}` : ""}">
      <h4>${escapeHtml(title)}</h4>
      ${body}
    </div>
  `;
}

function renderSpecificActivitiesHtml(activities: LessonPlanDay["specificActivities"]) {
  const entries = Object.entries(activities || {}).filter(([, value]) => Boolean(value));
  if (!entries.length) return "";
  return `
    <section class="section">
      <h3>Specific Activities</h3>
      ${entries.map(([phase, raw]) => {
        const activity = raw as any;
        if (!activity) return "";
        if (phase === "ACTIVITY") {
          const cards: string[] = [];
          if (sanitize(activity.readingPassage)) {
            cards.push(renderCard(
              `${phase} - ${activity.type || "Activity"} Reading`,
              `<p><strong>Reading Passage:</strong> ${escapeHtml(activity.readingPassage)}</p>`,
              { threshold: 700 }
            ));
          }
          (activity.questions || []).forEach((q: any, index: number) => {
            cards.push(renderCard(
              `${phase} Question ${index + 1}`,
              `<p><strong>Q${index + 1}:</strong> ${escapeHtml(q?.question)}</p><p class="item"><strong>Answer:</strong> ${escapeHtml(q?.answer)}</p>`
            ));
          });
          return cards.join("");
        }
        if (phase === "ANALYSIS") {
          const cards: string[] = [];
          (activity.trueFalse || []).forEach((tf: any, index: number) => {
            cards.push(renderCard(
              `${phase} Item ${index + 1}`,
              `<p><strong>${index + 1}.</strong> ${escapeHtml(tf?.statement)}</p><p class="item"><strong>Expected:</strong> ${escapeHtml(tf?.answer)}</p><p class="item"><strong>Explanation:</strong> ${escapeHtml(tf?.explanation)}</p>`
            ));
          });
          if ((activity.checklist || []).length) {
            cards.push(renderCard(
              `${phase} Checklist`,
              renderList(activity.checklist),
              { threshold: 650 }
            ));
          }
          return cards.join("");
        }
        if (phase === "ABSTRACTION") {
          const cards: string[] = [];
          if ((activity.pairs || []).length) {
            cards.push(renderCard(
              `${phase} Pairs`,
              `<ul>${(activity.pairs || []).map((pair: any) => `<li>${escapeHtml(pair?.left)} &rarr; ${escapeHtml(pair?.right)}</li>`).join("")}</ul>`,
              { threshold: 650 }
            ));
          }
          if (sanitize(activity.explanation)) {
            cards.push(renderCard(
              `${phase} Explanation`,
              `<p><strong>Explanation:</strong> ${escapeHtml(activity.explanation)}</p>`,
              { threshold: 700 }
            ));
          }
          return cards.join("");
        }
        if (phase === "APPLICATION") {
          const cards: string[] = [];
          (activity.multipleChoice || []).forEach((mc: any, index: number) => {
            cards.push(renderCard(
              `${phase} Question ${index + 1}`,
              `
                <p><strong>Q${index + 1}:</strong> ${escapeHtml(mc?.question)}</p>
                ${renderList((mc?.options || []).map((option: string, optionIndex: number) => `${String.fromCharCode(97 + optionIndex)}) ${option}`))}
                <p class="item"><strong>Answer:</strong> ${escapeHtml(mc?.answer)}</p>
                <p class="item"><strong>Explanation:</strong> ${escapeHtml(mc?.explanation)}</p>
              `,
              { threshold: 720 }
            ));
          });
          const clues = activity.identification?.clues || [];
          const answers = activity.identification?.answers || [];
          clues.forEach((clue: string, index: number) => {
            cards.push(renderCard(
              `${phase} Clue ${index + 1}`,
              `<p><strong>Clue ${index + 1}:</strong> ${escapeHtml(clue)}</p><p class="item"><strong>Answer:</strong> ${escapeHtml(answers[index])}</p>`
            ));
          });
          return cards.join("");
        }
        return "";
      }).join("")}
    </section>
  `;
}

function renderLessonPlanPdfHtml(lessonPlan: LessonPlanData, topic: string) {
  const framework = getLessonPlanFramework(lessonPlan?.framework);
  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        @page { size: A4; margin: 18mm 14mm 18mm 14mm; }
        :root { color-scheme: light; }
        body {
          font-family: Arial, Helvetica, sans-serif;
          color: #1e293b;
          margin: 0;
          font-size: 11px;
          line-height: 1.45;
          background: white;
        }
        h1,h2,h3,h4,p,ul,ol { margin: 0; }
        h1, h2, h3, h4 {
          break-after: avoid-page;
          page-break-after: avoid;
        }
        p, li {
          orphans: 3;
          widows: 3;
        }
        .page { display: block; }
        .hero {
          padding: 18px 20px;
          border-radius: 16px;
          background: linear-gradient(135deg, #eff6ff, #ffffff);
          border: 1px solid #dbeafe;
          margin-bottom: 18px;
        }
        .hero h1 {
          font-size: 24px;
          line-height: 1.15;
          color: #0f172a;
          margin-bottom: 8px;
        }
        .meta {
          color: #475569;
          font-size: 11px;
        }
        .section {
          margin-bottom: 18px;
          break-inside: auto;
        }
        .section > h2, .section > h3 {
          color: #1e3a8a;
          margin-bottom: 8px;
        }
        .section > h2 { font-size: 16px; }
        .section > h3 { font-size: 13px; }
        .day { margin-bottom: 22px; }
        .phase-grid {
          display: grid;
          grid-template-columns: 1fr;
          gap: 10px;
        }
        .card, .phase-card {
          border: 1px solid #dbe4f0;
          border-radius: 12px;
          padding: 12px 14px;
          background: #ffffff;
          box-shadow: 0 6px 20px rgba(15, 23, 42, 0.05);
        }
        .phase-card h4, .card h4 {
          color: #0f172a;
          font-size: 12px;
          margin-bottom: 6px;
        }
        .item { margin-top: 8px; }
        ul, ol { padding-left: 18px; margin-top: 6px; }
        li { margin: 4px 0; }
        .avoid-break { break-inside: avoid; page-break-inside: avoid; }
        .keep-with-next {
          break-after: avoid-page;
          page-break-after: avoid;
        }
        .section > h2 + *,
        .section > h3 + *,
        .card > h4 + *,
        .phase-card > h4 + * {
          break-before: avoid-page;
          page-break-before: avoid;
        }
        .muted { color: #64748b; }
        .footer {
          position: running(pageFooter);
        }
      </style>
    </head>
    <body>
      <main class="page">
        <section class="hero avoid-break">
          <h1>${escapeHtml(sanitize(lessonPlan?.title) || "Lesson Plan")}</h1>
          <p class="meta">Grade: ${escapeHtml(lessonPlan?.grade)} | Duration: ${escapeHtml(lessonPlan?.duration)}</p>
          ${sanitize(topic) ? `<p class="meta" style="margin-top:4px;">Topic: ${escapeHtml(topic)}</p>` : ""}
          <p class="meta" style="margin-top:4px;">Framework: ${escapeHtml(lessonPlan?.frameworkLabel || framework.label)}</p>
        </section>

        ${(lessonPlan?.objectives || []).length ? `
          <section class="section avoid-break">
            <h2>Learning Objectives</h2>
            ${renderList(lessonPlan.objectives, true)}
          </section>
        ` : ""}

        ${(lessonPlan?.days || []).map((day) => `
          <section class="day">
            <div class="section keep-with-next">
              <h2>Day ${day.day}: ${escapeHtml(day.topic)}</h2>
              <p class="muted">${escapeHtml(lessonPlan?.frameworkLabel || framework.sectionTitle)}</p>
            </div>

            <section class="section">
              <div class="phase-grid">
                ${(day["4asModel"] || []).map((phase) => `
                  <div class="${shouldAvoidBreak(`${phase.phase} ${phase.title} ${phase.description} ${phase.teacherRole} ${phase.studentRole} ${(phase.materials || []).join(" ")}`, 620) ? "phase-card avoid-break" : "phase-card"}">
                    <h4>${escapeHtml(phase.phase)} - ${escapeHtml(phase.title)} (${Number(phase.timeMinutes || 0)} min)</h4>
                    <p><strong>Description:</strong> ${escapeHtml(phase.description)}</p>
                    <p class="item"><strong>Teacher Role:</strong> ${escapeHtml(phase.teacherRole)}</p>
                    <p class="item"><strong>Student Role:</strong> ${escapeHtml(phase.studentRole)}</p>
                    <p class="item"><strong>Materials:</strong> ${escapeHtml((phase.materials || []).join(", "))}</p>
                  </div>
                `).join("")}
              </div>
            </section>

            ${renderSpecificActivitiesHtml(day.specificActivities || {})}

            ${(day.assessment || []).length ? `
              <section class="section">
                <h3>Assessment and Rubrics</h3>
                ${(day.assessment || []).map((assessment) => `
                  ${renderCard(
                    assessment.criteria || "Assessment",
                    `<p><strong>Description:</strong> ${escapeHtml(assessment.description)}</p>
                    <p class="item"><strong>Excellent:</strong> ${escapeHtml(assessment.rubricLevel?.excellent || "")}</p>
                    <p class="item"><strong>Satisfactory:</strong> ${escapeHtml(assessment.rubricLevel?.satisfactory || "")}</p>
                    <p class="item"><strong>Needs Improvement:</strong> ${escapeHtml(assessment.rubricLevel?.needsImprovement || "")}</p>`,
                    { threshold: 760 }
                  )}
                `).join("")}
              </section>
            ` : ""}

            ${sanitize(day.differentiation) ? `
              <section class="section ${shouldAvoidBreak(day.differentiation, 700) ? "avoid-break" : ""}">
                <h3>Differentiation</h3>
                <p>${escapeHtml(day.differentiation)}</p>
              </section>
            ` : ""}

            ${sanitize(day.closure) ? `
              <section class="section ${shouldAvoidBreak(day.closure, 700) ? "avoid-break" : ""}">
                <h3>Closure</h3>
                <p>${escapeHtml(day.closure)}</p>
              </section>
            ` : ""}
          </section>
        `).join("")}
      </main>
    </body>
  </html>`;
}

async function generateLessonPlanPDFWithHtml(
  lessonPlan: LessonPlanData,
  topic: string
): Promise<Buffer> {
  const html = renderLessonPlanPdfHtml(lessonPlan, topic);
  const playwrightModule = await import("playwright").catch(() => null as any);
  if (!playwrightModule?.chromium) {
    throw new Error("Playwright is not available for HTML PDF generation.");
  }
  const browser = await playwrightModule.chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "12mm",
        right: "10mm",
        bottom: "12mm",
        left: "10mm",
      },
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

async function generateLessonPlanPDFWithPdfKit(
  lessonPlan: LessonPlanData,
  topic: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const framework = getLessonPlanFramework(lessonPlan?.framework);
      const doc = new PDFDocument({
        margin: MARGIN,
        size: "A4",
        bufferPages: true,
        info: {
          Title: `Lesson Plan: ${sanitize(lessonPlan?.title) || "Lesson Plan"}`,
          Author: "QuizMintAI",
          Subject: "Lesson Plan",
          Creator: "QuizMintAI",
          Producer: "QuizMintAI PDF Export",
          CreationDate: new Date(),
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk) => chunks.push(chunk as Buffer));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const title = sanitize(lessonPlan?.title) || "Lesson Plan";
      heading(doc, title, 1);
      paragraph(doc, `Grade: ${sanitize(lessonPlan?.grade)} | Duration: ${sanitize(lessonPlan?.duration)}`, {
        size: 10,
        color: "#1e293b",
      });
      if (sanitize(topic)) paragraph(doc, `Topic: ${sanitize(topic)}`, { size: 10, color: "#475569" });

      if ((lessonPlan?.objectives || []).length) {
        heading(doc, "Learning Objectives", 2);
        for (const [i, objective] of lessonPlan.objectives.entries()) {
          bullet(doc, `${i + 1}. ${objective}`);
        }
      }

      for (const day of lessonPlan?.days || []) {
        heading(doc, `Day ${day.day}: ${sanitize(day.topic)}`, 2);
        heading(doc, lessonPlan?.frameworkLabel || framework.sectionTitle, 3);
        for (const phase of day["4asModel"] || []) {
          heading(
            doc,
            `${sanitize(phase.phase)} - ${sanitize(phase.title)} (${Number(phase.timeMinutes || 0)} min)`,
            3
          );
          labeledParagraph(doc, "Description", phase.description);
          labeledParagraph(doc, "Teacher Role", phase.teacherRole);
          labeledParagraph(doc, "Student Role", phase.studentRole);
          labeledParagraph(doc, "Materials", (phase.materials || []).join(", "));
        }

        if (Object.keys(day.specificActivities || {}).length > 0) {
          renderSpecificActivities(doc, day.specificActivities || {});
        }

        if ((day.assessment || []).length) {
          heading(doc, "Assessment and Rubrics", 2);
          for (const assessment of day.assessment) {
            heading(doc, sanitize(assessment.criteria || "Assessment"), 3);
            labeledParagraph(doc, "Description", assessment.description);
            labeledParagraph(doc, "Excellent", assessment.rubricLevel?.excellent || "");
            labeledParagraph(doc, "Satisfactory", assessment.rubricLevel?.satisfactory || "");
            labeledParagraph(doc, "Needs Improvement", assessment.rubricLevel?.needsImprovement || "");
          }
        }

        if (sanitize(day.differentiation)) {
          heading(doc, "Differentiation", 2);
          paragraph(doc, day.differentiation);
        }
        if (sanitize(day.closure)) {
          heading(doc, "Closure", 2);
          paragraph(doc, day.closure);
        }
      }

      addFooter(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export async function generateLessonPlanPDF(
  lessonPlan: LessonPlanData,
  topic: string
): Promise<Buffer> {
  const preferHtml = process.env.LESSON_PLAN_PDF_ENGINE !== "pdfkit";
  if (preferHtml) {
    try {
      return await generateLessonPlanPDFWithHtml(lessonPlan, topic);
    } catch (error) {
      console.warn("[lesson-plan-pdf] html export failed, falling back to PDFKit:", error);
    }
  }
  return generateLessonPlanPDFWithPdfKit(lessonPlan, topic);
}
