import PDFDocument from "pdfkit";
import { Buffer } from "buffer";

export interface LessonPlanDay {
  day: number;
  topic: string;
  "4asModel": Array<{
    phase: string;
    title: string;
    timeMinutes: number;
    description: string;
    teacherRole: string;
    studentRole: string;
    materials: string[];
  }>;
  specificActivities: {
    ACTIVITY?: {
      type: string;
      readingPassage: string;
      questions: Array<{ question: string; answer: string }>;
    };
    ANALYSIS?: {
      type: string;
      trueFalse: Array<{ statement: string; answer: string; explanation: string }>;
      checklist: string[];
    };
    ABSTRACTION?: {
      type: string;
      pairs: Array<{ left: string; right: string }>;
      explanation: string;
    };
    APPLICATION?: {
      type: string;
      multipleChoice: Array<{
        question: string;
        options: string[];
        answer: string;
        explanation: string;
      }>;
      identification: { clues: string[]; wordBank: string[]; answers: string[] };
    };
  };
  assessment: Array<{
    criteria: string;
    description: string;
    rubricLevel: {
      excellent: string;
      satisfactory: string;
      needsImprovement: string;
    };
  }>;
  differentiation: string;
  closure: string;
}

export interface LessonPlanData {
  title: string;
  grade: string;
  duration: string;
  objectives: string[];
  days: LessonPlanDay[];
}

const MARGIN = 54;
const CONTENT_WIDTH = 612 - MARGIN * 2;

function sanitize(text: unknown): string {
  return String(text ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

function ensureSpace(doc: PDFKit.PDFDocument, needed = 28) {
  const usableBottom = doc.page.height - doc.page.margins.bottom - 20;
  if (doc.y + needed > usableBottom) doc.addPage();
}

function heading(doc: PDFKit.PDFDocument, text: string, level: 1 | 2 | 3 = 2) {
  ensureSpace(doc, level === 1 ? 40 : 30);
  const size = level === 1 ? 18 : level === 2 ? 14 : 11;
  const color = level === 1 ? "#0f172a" : "#1e3a8a";
  doc.font("Helvetica-Bold").fontSize(size).fillColor(color).text(text, MARGIN, doc.y, {
    width: CONTENT_WIDTH,
  });
  doc.moveDown(level === 1 ? 0.55 : 0.35);
}

function paragraph(doc: PDFKit.PDFDocument, text: string, opts?: { size?: number; color?: string }) {
  const value = sanitize(text);
  if (!value) return;
  ensureSpace(doc, 20);
  doc
    .font("Helvetica")
    .fontSize(opts?.size ?? 10)
    .fillColor(opts?.color ?? "#334155")
    .text(value, MARGIN, doc.y, { width: CONTENT_WIDTH, lineGap: 2, align: "left" });
  doc.moveDown(0.22);
}

function labeledParagraph(doc: PDFKit.PDFDocument, label: string, value: string) {
  const clean = sanitize(value);
  if (!clean) return;
  ensureSpace(doc, 22);
  doc
    .font("Helvetica-Bold")
    .fontSize(9.5)
    .fillColor("#0f172a")
    .text(`${label}: `, MARGIN, doc.y, { continued: true });
  doc.font("Helvetica").fontSize(9.5).fillColor("#334155").text(clean, {
    width: CONTENT_WIDTH,
    lineGap: 2,
  });
  doc.moveDown(0.1);
}

function bullet(doc: PDFKit.PDFDocument, text: string, indent = 0) {
  const clean = sanitize(text);
  if (!clean) return;
  ensureSpace(doc, 20);
  const x = MARGIN + indent;
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#1d4ed8").text("•", x, doc.y, { continued: true });
  doc.font("Helvetica").fontSize(10).fillColor("#334155").text(` ${clean}`, {
    width: CONTENT_WIDTH - indent - 8,
    lineGap: 2,
  });
}

function addFooter(doc: PDFKit.PDFDocument) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    const y = doc.page.height - 26;
    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor("#64748b")
      .text(`Page ${i + 1} of ${range.count}`, MARGIN, y, { width: CONTENT_WIDTH / 2, align: "left" });
    doc
      .font("Helvetica-Oblique")
      .fontSize(8.5)
      .fillColor("#94a3b8")
      .text("Generated by QuizMintAI", MARGIN + CONTENT_WIDTH / 2, y, {
        width: CONTENT_WIDTH / 2,
        align: "right",
      });
  }
}

function renderSpecificActivities(doc: PDFKit.PDFDocument, activities: LessonPlanDay["specificActivities"]) {
  const entries = Object.entries(activities || {});
  if (!entries.length) return;
  heading(doc, "Specific Activities", 2);

  for (const [phase, raw] of entries) {
    const activity = raw as any;
    if (!activity) continue;
    heading(doc, `${phase} - ${sanitize(activity.type || "Activity")}`, 3);

    if (phase === "ACTIVITY") {
      labeledParagraph(doc, "Reading Passage", activity.readingPassage);
      for (const [i, q] of (activity.questions || []).entries()) {
        bullet(doc, `Q${i + 1}: ${sanitize(q?.question)}`);
        labeledParagraph(doc, "Answer", sanitize(q?.answer));
      }
    }

    if (phase === "ANALYSIS") {
      for (const [i, tf] of (activity.trueFalse || []).entries()) {
        bullet(doc, `${i + 1}. ${sanitize(tf?.statement)}`);
        labeledParagraph(doc, "Expected", sanitize(tf?.answer));
        labeledParagraph(doc, "Explanation", sanitize(tf?.explanation));
      }
      for (const item of activity.checklist || []) bullet(doc, item);
    }

    if (phase === "ABSTRACTION") {
      for (const pair of activity.pairs || []) {
        bullet(doc, `${sanitize(pair?.left)} -> ${sanitize(pair?.right)}`);
      }
      labeledParagraph(doc, "Explanation", sanitize(activity.explanation));
    }

    if (phase === "APPLICATION") {
      for (const [i, mc] of (activity.multipleChoice || []).entries()) {
        bullet(doc, `Q${i + 1}: ${sanitize(mc?.question)}`);
        for (const [idx, option] of (mc?.options || []).entries()) {
          const letter = String.fromCharCode(97 + idx);
          bullet(doc, `${letter}) ${sanitize(option)}`, 14);
        }
        labeledParagraph(doc, "Answer", sanitize(mc?.answer));
        labeledParagraph(doc, "Explanation", sanitize(mc?.explanation));
      }

      const clues = activity.identification?.clues || [];
      const answers = activity.identification?.answers || [];
      for (const [i, clue] of clues.entries()) {
        bullet(doc, `Clue ${i + 1}: ${sanitize(clue)}`);
        labeledParagraph(doc, "Answer", sanitize(answers[i]));
      }
    }

    doc.moveDown(0.25);
  }
}

export async function generateLessonPlanPDF(
  lessonPlan: LessonPlanData,
  topic: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: MARGIN,
        size: "A4",
        bufferPages: true,
        info: {
          Title: `Lesson Plan: ${sanitize(lessonPlan?.title) || "Lesson Plan"}`,
          Author: "QuizMintAI",
          Subject: "Lesson Plan",
          Creator: "QuizMintAI",
          Producer: "QuizMintAI PDF Export",
          CreationDate: new Date(),
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk) => chunks.push(chunk as Buffer));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const title = sanitize(lessonPlan?.title) || "Lesson Plan";
      heading(doc, title, 1);
      paragraph(doc, `Grade: ${sanitize(lessonPlan?.grade)} | Duration: ${sanitize(lessonPlan?.duration)}`, {
        size: 10,
        color: "#1e293b",
      });
      if (sanitize(topic)) paragraph(doc, `Topic: ${sanitize(topic)}`, { size: 10, color: "#475569" });

      if ((lessonPlan?.objectives || []).length) {
        heading(doc, "Learning Objectives", 2);
        for (const [i, objective] of lessonPlan.objectives.entries()) {
          bullet(doc, `${i + 1}. ${objective}`);
        }
      }

      for (const day of lessonPlan?.days || []) {
        heading(doc, `Day ${day.day}: ${sanitize(day.topic)}`, 2);
        heading(doc, "4A's Pedagogical Framework", 3);
        for (const phase of day["4asModel"] || []) {
          heading(
            doc,
            `${sanitize(phase.phase)} - ${sanitize(phase.title)} (${Number(phase.timeMinutes || 0)} min)`,
            3
          );
          labeledParagraph(doc, "Description", phase.description);
          labeledParagraph(doc, "Teacher Role", phase.teacherRole);
          labeledParagraph(doc, "Student Role", phase.studentRole);
          labeledParagraph(doc, "Materials", (phase.materials || []).join(", "));
        }

        renderSpecificActivities(doc, day.specificActivities || {});

        if ((day.assessment || []).length) {
          heading(doc, "Assessment and Rubrics", 2);
          for (const assessment of day.assessment) {
            heading(doc, sanitize(assessment.criteria || "Assessment"), 3);
            labeledParagraph(doc, "Description", assessment.description);
            labeledParagraph(doc, "Excellent", assessment.rubricLevel?.excellent || "");
            labeledParagraph(doc, "Satisfactory", assessment.rubricLevel?.satisfactory || "");
            labeledParagraph(doc, "Needs Improvement", assessment.rubricLevel?.needsImprovement || "");
          }
        }

        if (sanitize(day.differentiation)) {
          heading(doc, "Differentiation", 2);
          paragraph(doc, day.differentiation);
        }
        if (sanitize(day.closure)) {
          heading(doc, "Closure", 2);
          paragraph(doc, day.closure);
        }
      }

      addFooter(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
